behaviors:
  MeleeAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 32
      buffer_size: 512
      learning_rate: 0.001
      beta: 0.001
      epsilon: 0.2
      lambd: 0.9
      num_epoch: 1
    network_settings:
      hidden_units: 32
      num_layers: 1
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 5000
    time_horizon: 32
    summary_freq: 1000
